backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # תיקייה למדיה שתעלה ל-CMS
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "פרויקטים"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { label: "תיאור", name: "description", widget: "text" }
      - { label: "תמונה", name: "image", widget: "image" }
      - { label: "תוכן", name: "body", widget: "markdown" }
